DROP TABLE IF EXISTS TB_HEROIS;
CREATE TABLE TB_HEROIS {
  ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
  NAME TEXT NOT NULL,
  POWER TEXT NOT NULL,
}

-- create
INSERT INTO TB_HEROIS (NAME, POWER)
VALUES
  ('Flash', 'Speed'),
  ('Aquaman', 'Talk to animals'),
  ('Batman', 'Money')

-- read
SELECT * FROM TB_HEROIS;
SELECT * FROM TB_HEROIS WHERE NAME = 'Flash';

-- update
ALTER TABLE TB_HEROIS
RENAME COLUMN PODER TO POWER; 

UPDATE TB_HEROIS
SET NAME = 'Goku', POWER = 'God'
WHERE ID = 1;

-- delete
DELETE FROM TB_HEROIS WHERE ID = 2;